name: "Swift Build & Test"

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4

    - name: Install SwiftLint
      run: |
        brew install swiftlint

    - name: Build
      run: |
        xcodebuild build-for-testing \
          -project MarmotMonitor.xcodeproj \
          -scheme MarmotMonitor \
          -destination "platform=iOS Simulator,name=iPhone 16"

    - name: Test
      run: |
        xcodebuild test-without-building \
          -project MarmotMonitor.xcodeproj \
          -scheme MarmotMonitor \
          -destination "platform=iOS Simulator,name=iPhone 16,OS=18.0" \
          | xcpretty && exit ${PIPESTATUS[0]}
