name: "Swift Build on push"

on: [push]

jobs:
  build-and-test:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4

    - name: Install SwiftLint
      run: |
        brew install swiftlint

    - name: Build
      run: |
        xcodebuild build-for-testing \
          -project MarmotMonitor.xcodeproj \
          -scheme MarmotMonitor \
          -destination "platform=iOS Simulator,name=iPhone 16"
